spring:
  datasource:
    url: jdbc:hsqldb:hsql://localhost/testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
app:
  spring-boot-template.base-url: http://localhost:8080