spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springboot_template
    username: yaphet
    password: root
  jpa:
    hibernate:
#      ddl-auto: validate
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
app:
  spring-boot-template.base-url: